name: 构建 Magisk 模块

on:
  workflow_dispatch:
    inputs:
      rom:
        description: 'ROM 版本号 (e.g., OS2.0.202.0.VOZCNXM)'
        required: true
      url:
        description: 'ROM 下载链接'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 克隆仓库
        uses: actions/checkout@v6.0.2

      - name: 🛠 安装依赖
        run: |
          sudo apt update
          sudo apt-get install -y zip unzip

      - name: 🧪 构建模块
        run: |
          bash ./build.sh --rom "${{ github.event.inputs.rom }}" \
                          --url "${{ github.event.inputs.url }}"

      - name: 📦 上传构建产物
        uses: actions/upload-artifact@v7.0.0
        with:
          name: "${{ github.event.inputs.rom }}"
          path: tmp/release/
